### ISSUE TITLE
Update to a generic FOSTIVE branding

### ISSUE THREAD

**Issue by julianduque** [fostive/emote-widget#28]
- [ ] Add a Powered by Fostive linking to the GitHub repo
- [ ] Change colors to Fostive brand
- [ ] Remove other event logos and branding
- [ ] Add documentation on **How to customize the emote-widget app**
- [ ] Update Emotes to use Fostive colors (@DianaPerkinsDesign)

**Comment by DianaPerkinsDesign** [comment]
Cool! I can handle this one. Do you have those brand assets (preferably vector) @superhighfives ?

**Comment by superhighfives** [comment]
[Fostive (Master @ 6bbe8f9).sketch.zip](https://github.com/fostive/emote-widget/files/5173657/Fostive.Master.%40.6bbe8f9.sketch.zip) attached @DianaPerkinsDesign. 🙌 Let me know if I can provide anything else. https://fonts.google.com/specimen/Krona+One is the font.

**Comment by superhighfives** [comment]
There's also a related PR for this one here, @DianaPerkinsDesign: https://github.com/fostive/gif-booth/issues/24 Would be good to do both at the same time. 👍

**Comment by superhighfives** [comment]
(Added you to the repo, @DianaPerkinsDesign, too.)

**Comment by DianaPerkinsDesign** [comment]
@julianduque @superhighfives I think this one might be complete! 🎉  🎉

**Comment by superhighfives** [comment]
Great! In that case, will close. Thanks @DianaPerkinsDesign. 🙌
