### ISSUE TITLE
Unable to run the build and watch commands

### ISSUE THREAD

**Issue by adityanaag3** [fostive/emote-widget#32]
Did a fresh clone of the repo, and ran the `npm run watch` command. It failed with the below error
`Error: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.`
Same is the case with the `build` command.

**Comment by crcastle** [comment]
Hey @adityanaag3! I'm unable to reproduce this. What version of node and npm are you using?

**Comment by adityanaag3** [comment]
@crcastle npm `6.4.1` and node `10.15.3`

**Comment by julianduque** [comment]
@adityanaag3 can you try with Node.js v12 LTS?

**Comment by adityanaag3** [comment]
Updated to `12.19.0` and still the same. Is there any pre-requisite? I didn't set up the server by the way.. Do you think that's causing a problem?

**Comment by crcastle** [comment]
Hmmm.... I also was unable to reproduce the bug on my machine using the versions you have (Node 10.15.3 and npm 6.4.1).

This is intriguing. Are you on Windows @adityanaag3?

**Comment by adityanaag3** [comment]
Nope, I am on mac.

**Comment by crcastle** [comment]
@adityanaag3 I emailed you. Let's do a screen share and figure this out!
